<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!--
  Author: Kelsey Hawkins
  Contributers: Jimmy Da Silva, Ajit Krisshna N L, Muhammad Asif Rana
-->

  <xacro:include filename="$(find ur_e_description)/urdf/ur.transmission.xacro" />
  <xacro:include filename="$(find ur_e_description)/urdf/ur.gazebo.xacro" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="ur10e_robot" params="prefix joint_limited
    shoulder_pan_lower_limit:=${-pi}    shoulder_pan_upper_limit:=${pi}
    shoulder_lift_lower_limit:=${-pi}    shoulder_lift_upper_limit:=${pi}
    elbow_joint_lower_limit:=${-pi}    elbow_joint_upper_limit:=${pi}
    wrist_1_lower_limit:=${-pi}    wrist_1_upper_limit:=${pi}
    wrist_2_lower_limit:=${-pi}    wrist_2_upper_limit:=${pi}
    wrist_3_lower_limit:=${-pi}    wrist_3_upper_limit:=${pi}
    transmission_hw_interface:=hardware_interface/PositionJointInterface
    safety_limits:=false safety_pos_margin:=0.15
    safety_k_position:=20">

    <!-- Inertia parameters -->
    <xacro:property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
    <xacro:property name="shoulder_mass" value="7.778" />
    <xacro:property name="upper_arm_mass" value="12.93" />
    <xacro:property name="forearm_mass" value="3.87" />
    <xacro:property name="wrist_1_mass" value="1.96" />
    <xacro:property name="wrist_2_mass" value="1.96" />
    <xacro:property name="wrist_3_mass" value="0.202" />

    <!-- These parameters are borrowed from the urcontrol.conf file
        but are not verified for the correct permutation.
        The permutation was guessed by looking at the ur5e parameters.
        Serious use of these parameters needs further inspection. -->
    <xacro:property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
    <xacro:property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
    <xacro:property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
    <xacro:property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
    <xacro:property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
    <xacro:property name="wrist_3_cog" value="0 -0.001156 -0.00149" />

    <!-- Kinematic model -->
    <!-- Properties from urcontrol.conf -->
    <xacro:property name="d1" value="0.181" />
    <xacro:property name="a2" value="-0.613" />
    <xacro:property name="a3" value="-0.571" />
    <xacro:property name="d4" value="0.135" />
    <xacro:property name="d5" value="0.120" />
    <xacro:property name="d6" value="0.117" />

    <!-- Arbitrary offsets for shoulder/elbow joints -->
    <xacro:property name="shoulder_offset" value="0.176" />
    <xacro:property name="elbow_offset" value="-0.137" />

    <!-- link lengths used in model -->
    <xacro:property name="shoulder_height" value="${d1}" />
    <xacro:property name="upper_arm_length" value="${-a2}" />
    <xacro:property name="forearm_length" value="${-a3}" />
    <xacro:property name="wrist_1_length" value="${d4}" />
    <xacro:property name="wrist_2_length" value="${d5}" />
    <xacro:property name="wrist_3_length" value="${d6}" />

    <link name="${prefix}base_link" >
      <visual>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/visual/base.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/collision/base.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${base_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="3.14"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="330.0" velocity="3.14"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${shoulder_pan_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_pan_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/visual/shoulder.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/collision/shoulder.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_lift_joint" type="revolute">
      <parent link="${prefix}shoulder_link" />
      <child link = "${prefix}upper_arm_link" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="3.14"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}" effort="330.0" velocity="3.14"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${shoulder_lift_lower_limit + safety_pos_margin}" soft_upper_limit="${shoulder_lift_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/visual/upperarm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/collision/upperarm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 ${-a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}elbow_joint" type="revolute">
      <parent link="${prefix}upper_arm_link" />
      <child link = "${prefix}forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.14"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}" effort="150.0" velocity="3.14"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${elbow_joint_lower_limit + safety_pos_margin}" soft_upper_limit="${elbow_joint_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}forearm_link">
      <visual>
         <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/visual/forearm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/collision/forearm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_1_joint" type="revolute">
      <parent link="${prefix}forearm_link" />
      <child link = "${prefix}wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="6.28"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}" effort="54.0" velocity="6.28"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_1_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_1_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/visual/wrist1.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/collision/wrist1.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_2_joint" type="revolute">
      <parent link="${prefix}wrist_1_link" />
      <child link = "${prefix}wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="6.28"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}" effort="54.0" velocity="6.28"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_2_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_2_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/visual/wrist2.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/collision/wrist2.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_3_joint" type="revolute">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}wrist_3_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="6.28"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${-2.0 * pi + safety_pos_margin}" soft_upper_limit="${2.0 * pi - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="54.0" velocity="6.28"/>
        <xacro:if value="${safety_limits}">
          <safety_controller soft_lower_limit="${wrist_3_lower_limit + safety_pos_margin}" soft_upper_limit="${wrist_3_upper_limit - safety_pos_margin}" k_position="${safety_k_position}" k_velocity="0.0"/>
        </xacro:if>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/visual/wrist3.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_e_description/meshes/ur10e/collision/wrist3.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.045" length="0.05" mass="${wrist_3_mass}">
        <origin xyz="0.0 ${wrist_3_length - 0.05/2} 0.0" rpy="${pi/2} 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}ee_fixed_joint" type="fixed">
      <parent link="${prefix}wrist_3_link" />
      <child link = "${prefix}ee_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${prefix}ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
    </link>

    <joint
    name="finger1_base_joint"
    type="revolute">
    <origin
      xyz="-0.0161724988655456 0.0279961367597022 0.105"
      rpy="0 0 0.523598783277495" />
    <parent
      link="ee_link" />
    <child
      link="finger1_base_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-1"
      upper="0.54"
      effort="100"
      velocity="100" />
  </joint>
  <link
    name="finger1_Link">
    <inertial>
      <origin
        xyz="0.0210050434938139 0.012249999999974 0.0178290357798672"
        rpy="0 0 0" />
      <mass
        value="0.00557906977988049" />
      <inertia
        ixx="8.99405333082292E-07"
        ixy="9.82637628153793E-19"
        ixz="-5.95537945974777E-07"
        iyy="1.3061675562027E-06"
        iyz="6.37604051045675E-19"
        izz="1.24905466077277E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger1_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.0549019607843137 0.0549019607843137 0.0549019607843137 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger1_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger1_joint"
    type="revolute">
    <origin
      xyz="0.01225 -0.0081568 0.0175"
      rpy="0 0 1.5708" />
    <parent
      link="finger1_base_Link" />
    <child
      link="finger1_Link" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="1.16"
      effort="100"
      velocity="100" />
  </joint>
  <link
    name="finger1_tip_Link">
    <inertial>
      <origin
        xyz="0.000977109926666546 0.0123819370127123 0.0136590907193947"
        rpy="0 0 0" />
      <mass
        value="0.0107564294883422" />
      <inertia
        ixx="1.48949781713587E-06"
        ixy="-7.10872889918193E-09"
        ixz="1.38025837549055E-07"
        iyy="1.35009809053808E-06"
        iyz="1.24264254163864E-08"
        izz="4.77788297009959E-07" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger1_tip_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger1_tip_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger1_tip_joint"
    type="revolute">
    <origin
      xyz="0.044029 0 0.032962"
      rpy="0 0 0" />
    <parent
      link="finger1_Link" />
    <child
      link="finger1_tip_Link" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="-1"
      upper="1"
      effort="100"
      velocity="100" />
    <mimic
      joint="finger1_joint"
      multiplier="-1"
      offset="0" />
  </joint>
  <link
    name="finger1_outlet_Link">
    <inertial>
      <origin
        xyz="0.0205745260056277 -0.00269403354044023 0.0154029170399833"
        rpy="0 0 0" />
      <mass
        value="0.00494212097275844" />
      <inertia
        ixx="3.17521820164163E-07"
        ixy="-1.11658813824013E-10"
        ixz="-3.22040978315679E-07"
        iyy="7.52126023069253E-07"
        iyz="-8.36396169396533E-11"
        izz="5.06597025546867E-07" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger1_outlet_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger1_outlet_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger1_outlet_joint"
    type="revolute">
    <origin
      xyz="-0.01035 0.0081568 0.0098929"
      rpy="0 0 1.5708" />
    <parent
      link="finger1_base_Link" />
    <child
      link="finger1_outlet_Link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
    <mimic
      joint="finger1_joint"
      multiplier="-1"
      offset="0" />
  </joint>
  <link
    name="finger2_base_Link">
    <inertial>
      <origin
        xyz="-0.000601794667086514 -0.00110288755052199 0.00521005597269419"
        rpy="0 0 0" />
      <mass
        value="0.00832299911583519" />
      <inertia
        ixx="9.16214830767147E-07"
        ixy="2.57171997885585E-08"
        ixz="1.43130193807236E-08"
        iyy="1.14280462688473E-06"
        iyz="5.78075867066608E-08"
        izz="1.77055158585084E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger2_base_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger2_base_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger2_base_joint"
    type="fixed">
    <origin
      xyz="0.032325 0 0.105"
      rpy="0 0 -1.5708" />
    <parent
      link="base_Link_dh3" />
    <child
      link="finger2_base_Link" />
    <axis
      xyz="0 0 0" />
  </joint>
  <link
    name="finger2_link">
    <inertial>
      <origin
        xyz="0.021005043493832 0.0122499999999494 0.0178290357798643"
        rpy="0 0 0" />
      <mass
        value="0.00557906977988033" />
      <inertia
        ixx="8.99405333082248E-07"
        ixy="1.40895930945985E-18"
        ixz="-5.95537945974751E-07"
        iyy="1.30616755620265E-06"
        iyz="1.47278790722963E-18"
        izz="1.24905466077276E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger2_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.0549019607843137 0.0549019607843137 0.0549019607843137 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger2_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger2_joint"
    type="revolute">
    <origin
      xyz="0.01225 -0.0081568 0.0175"
      rpy="0 0 1.5708" />
    <parent
      link="finger2_base_Link" />
    <child
      link="finger2_link" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
    <mimic
      joint="finger1_joint"
      multiplier="1"
      offset="0" />
  </joint>
  <link
    name="finger2_tip_Link">
    <inertial>
      <origin
        xyz="0.000977109970519835 0.0123819365363909 0.0136590906877767"
        rpy="0 0 0" />
      <mass
        value="0.0107564295938579" />
      <inertia
        ixx="1.48949781977635E-06"
        ixy="-7.10872109767472E-09"
        ixz="1.38025837268698E-07"
        iyy="1.35009809568266E-06"
        iyz="1.24264681742315E-08"
        izz="4.77788294510709E-07" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger2_tip_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger2_tip_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger2_tip_joint"
    type="revolute">
    <origin
      xyz="0.044029 0 0.032962"
      rpy="0 0 0" />
    <parent
      link="finger2_link" />
    <child
      link="finger2_tip_Link" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
    <mimic
      joint="finger1_tip_joint"
      multiplier="1"
      offset="0" />
  </joint>
  <link
    name="finger2_outlet_Link">
    <inertial>
      <origin
        xyz="0.0205745216753029 -0.00269403287328564 0.0154029129942138"
        rpy="0 0 0" />
      <mass
        value="0.00494212190694487" />
      <inertia
        ixx="3.17522151991331E-07"
        ixy="-1.11440245000629E-10"
        ixz="-3.22041349248125E-07"
        iyy="7.52126778397778E-07"
        iyz="-8.34843588255468E-11"
        izz="5.06597462640552E-07" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger2_outlet_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger2_outlet_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger2_outlet_joint"
    type="revolute">
    <origin
      xyz="-0.01035 0.0081568 0.0098929"
      rpy="0 0 1.5708" />
    <parent
      link="finger2_base_Link" />
    <child
      link="finger2_outlet_Link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
    <mimic
      joint="finger1_outlet_joint"
      multiplier="1"
      offset="0" />
  </joint>
  <link
    name="finger3_base_Link">
    <inertial>
      <origin
        xyz="-0.000601794667079381 -0.00110288755052597 0.00521005597269403"
        rpy="0 0 0" />
      <mass
        value="0.00832299911583507" />
      <inertia
        ixx="9.16214830766856E-07"
        ixy="2.57171997871098E-08"
        ixz="1.43130193803543E-08"
        iyy="1.1428046268851E-06"
        iyz="5.78075867067519E-08"
        izz="1.77055158585085E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger3_base_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger3_base_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger3_base_joint"
    type="revolute">
    <origin
      xyz="-0.016172 -0.028004 0.105"
      rpy="0 0 2.618" />
    <parent
      link="base_Link_dh3" />
    <child
      link="finger3_base_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
    <mimic
      joint="finger1_base_joint"
      multiplier="-1"
      offset="0" />
  </joint>
  <link
    name="finger3_Link">
    <inertial>
      <origin
        xyz="0.0210050434938141 0.012249999999974 0.0178290357798672"
        rpy="0 0 0" />
      <mass
        value="0.0055790697798808" />
      <inertia
        ixx="8.99405333082359E-07"
        ixy="9.61461081223117E-19"
        ixz="-5.95537945974827E-07"
        iyy="1.30616755620281E-06"
        iyz="6.24087927058166E-19"
        izz="1.24905466077285E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger3_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.0549019607843137 0.0549019607843137 0.0549019607843137 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger3_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger3_joint"
    type="revolute">
    <origin
      xyz="0.0122500000000007 -0.00815677008333035 0.0174999999999995"
      rpy="0 0 1.5707963267949" />
    <parent
      link="finger3_base_Link" />
    <child
      link="finger3_Link" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
    <mimic
      joint="finger1_joint"
      multiplier="1"
      offset="0" />
  </joint>
  <link
    name="finger3_tip_Link">
    <inertial>
      <origin
        xyz="0.000977114977738613 0.0123819369789457 0.01365909502715"
        rpy="0 0 0" />
      <mass
        value="0.0107564399961694" />
      <inertia
        ixx="1.48949935780095E-06"
        ixy="-7.10872801793197E-09"
        ixz="1.38025629536651E-07"
        iyy="1.35009963358183E-06"
        iyz="1.2426443300764E-08"
        izz="4.77788392346636E-07" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger3_tip_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger3_tip_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger3_tip_joint"
    type="revolute">
    <origin
      xyz="0.044029 0 0.032962"
      rpy="0 0 0" />
    <parent
      link="finger3_Link" />
    <child
      link="finger3_tip_Link" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
    <mimic
      joint="finger1_tip_joint"
      multiplier="1"
      offset="0" />
  </joint>
  <link
    name="finger3_outlet_Link">
    <inertial>
      <origin
        xyz="0.0205745375238259 -0.00269403304520632 0.0154029215009596"
        rpy="0 0 0" />
      <mass
        value="0.00494212514535466" />
      <inertia
        ixx="3.17522114051902E-07"
        ixy="-1.11543432026918E-10"
        ixz="-3.22041207812167E-07"
        iyy="7.52126509554002E-07"
        iyz="-8.35643256488424E-11"
        izz="5.0659720155034E-07" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger3_outlet_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh3_urdf/meshes/finger3_outlet_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger3_outlet_joint"
    type="revolute">
    <origin
      xyz="-0.01035 0.0081568 0.0098929"
      rpy="0 0 1.5708" />
    <parent
      link="finger3_base_Link" />
    <child
      link="finger3_outlet_Link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
    <mimic
      joint="finger1_outlet_joint"
      multiplier="1"
      offset="0" />
  </joint>

    <xacro:ur_arm_transmission prefix="${prefix}" />
    <xacro:ur_arm_gazebo prefix="${prefix}" />

    <!-- ROS base_link to UR 'Base' Coordinates transform -->
    <link name="${prefix}base"/>
    <joint name="${prefix}base_link-base_fixed_joint" type="fixed">
      <!-- NOTE: this rotation is only needed as long as base_link itself is
                 not corrected wrt the real robot (ie: rotated over 180
                 degrees)
      -->
      <origin xyz="0 0 0" rpy="0 0 ${-pi}"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base"/>
    </joint>

    <!-- Frame coincident with all-zeros TCP on UR controller -->
    <link name="${prefix}tool0"/>
    <joint name="${prefix}wrist_3_link-tool0_fixed_joint" type="fixed">
      <origin xyz="0 ${0.2135+wrist_3_length} 0" rpy="${pi/-2.0} 0 0"/>
      <parent link="${prefix}wrist_3_link"/>
      <child link="${prefix}tool0"/>
    </joint>

  </xacro:macro>
</robot>
